const fs = require("fs");
const lines = [];

lines.push("class SmcPaneRenderer implements IPrimitivePaneRenderer {");
lines.push("  private _dd: DrawData");
lines.push("  private _zone: ZoneCoords | null");
lines.push("");
lines.push("  constructor(dd: DrawData, zone: ZoneCoords | null) {");
lines.push("    this._dd = dd");
lines.push("    this._zone = zone");
lines.push("  }");
lines.push("");
lines.push("  draw(target: CanvasRenderingTarget2D): void {");
lines.push("    target.useMediaCoordinateSpace(({ context: ctx }) => {");
lines.push("      const d = this._dd");
lines.push("      for (const ob of d.orderBlocks) {");
lines.push("        ctx.fillStyle = ob.fillColor");
lines.push("        ctx.fillRect(ob.x1, ob.y1, ob.x2 - ob.x1, ob.y2 - ob.y1)");
lines.push("      }");
lines.push("      for (const fvg of d.fvgs) {");
lines.push("        ctx.fillStyle = FVG_FILL");
lines.push("        ctx.fillRect(fvg.x1, fvg.y1, fvg.x2 - fvg.x1, fvg.y2 - fvg.y1)");
lines.push("      }");
lines.push("      if (this._zone && d.orderBlocks.length > 0) {");
lines.push("        const z = this._zone");
lines.push("        const x1 = d.orderBlocks[0].x1");
lines.push("        const x2 = d.orderBlocks[d.orderBlocks.length - 1].x2");
lines.push('        ctx.fillStyle = "rgba(231,76,60,0.08)"');
lines.push("        ctx.fillRect(x1, z.premiumTop, x2 - x1, z.premiumBottom - z.premiumTop)");
lines.push('        ctx.fillStyle = "rgba(46,204,113,0.08)"');
lines.push("        ctx.fillRect(x1, z.discountTop, x2 - x1, z.discountBottom - z.discountTop)");
lines.push('        ctx.strokeStyle = "#95a5a6"');
lines.push("        ctx.lineWidth = 1");
lines.push("        ctx.beginPath()");
lines.push("        ctx.moveTo(x1, z.equilibrium)");
lines.push("        ctx.lineTo(x2, z.equilibrium)");
lines.push("        ctx.stroke()");
lines.push("      }");
lines.push('      ctx.strokeStyle = EQH_EQL_COLOR');
lines.push("      ctx.lineWidth = 1");
lines.push("      ctx.setLineDash([4, 4])");
lines.push("      for (const eqh of d.eqhLines) {");
lines.push("        ctx.beginPath()");
lines.push("        ctx.moveTo(eqh.x - 8, eqh.y)");
lines.push("        ctx.lineTo(eqh.x + 8, eqh.y)");
lines.push("        ctx.stroke()");
lines.push("      }");
lines.push("      for (const eql of d.eqlLines) {");
lines.push("        ctx.beginPath()");
lines.push("        ctx.moveTo(eql.x - 8, eql.y)");
lines.push("        ctx.lineTo(eql.x + 8, eql.y)");
lines.push("        ctx.stroke()");
lines.push("      }");
lines.push("      ctx.setLineDash([])");
lines.push("    })");
lines.push("  }");
lines.push("}");
lines.push("");

lines.push("class SmcPaneView implements IPrimitivePaneView {");
lines.push("  private _dd: DrawData");
lines.push("  private _zone: ZoneCoords | null");
lines.push("");
lines.push("  constructor(dd: DrawData, zone: ZoneCoords | null) {");
lines.push("    this._dd = dd");
lines.push("    this._zone = zone");
lines.push("  }");
lines.push("");
lines.push("  renderer(): IPrimitivePaneRenderer | null {");
lines.push("    return new SmcPaneRenderer(this._dd, this._zone)");
lines.push("  }");
lines.push("}");
lines.push("");

lines.push("class SmcPrimitive {");
lines.push("  private _chart: IChartApi | null = null");
lines.push('  private _series: ISeriesApi<"Line"> | null = null');
lines.push("  private _requestUpdate: (() => void) | null = null");
lines.push("  private _data: SmcBarResult[] = []");
lines.push("  private _colors: { bullFill: string; bearFill: string }");
lines.push("  private _barSec: number");
lines.push("  private _dd: DrawData = { orderBlocks: [], fvgs: [], eqhLines: [], eqlLines: [] }");
lines.push("  private _zone: ZoneCoords | null = null");
lines.push("");
lines.push("  constructor(colors: { bullFill: string; bearFill: string }, barSec: number) {");
lines.push("    this._colors = colors");
lines.push("    this._barSec = barSec");
lines.push("  }");
lines.push("");
lines.push('  attached(param: { chart: IChartApi; series: ISeriesApi<"Line">; requestUpdate: () => void }): void {');
lines.push("    this._chart = param.chart");
lines.push("    this._series = param.series");
lines.push("    this._requestUpdate = param.requestUpdate");
lines.push("  }");
lines.push("");
lines.push("  detached(): void {");
lines.push("    this._chart = null");
lines.push("    this._series = null");
lines.push("    this._requestUpdate = null");
lines.push("  }");
lines.push("");
lines.push("  setData(bars: SmcBarResult[]): void {");
lines.push("    this._data = bars");
lines.push("    this._requestUpdate?.()");
lines.push("  }");
lines.push("");
lines.push("  updateAllViews(): void {");
lines.push('    if (!this._chart || !this._series) return');
lines.push("    const chart = this._chart");
lines.push("    const series = this._series");
lines.push("    const obResult: ObRect[] = []");
lines.push("    const fvgResult: FvgRect[] = []");
lines.push("    const eqhLines: Array<{ x: number; y: number }> = []");
lines.push("    const eqlLines: Array<{ x: number; y: number }> = []");
lines.push("    let zoneResult: ZoneCoords | null = null");
lines.push("");
lines.push("    for (const bar of this._data) {");
lines.push("      const timeSec = bar.timestamp / 1000");
lines.push("      const barEndSec = timeSec + this._barSec");
lines.push("      const x = chart.timeScale().timeToCoordinate(timeSec as Time)");
lines.push("      const xR = chart.timeScale().timeToCoordinate(barEndSec as Time)");
lines.push("      if (x == null) continue");
lines.push("      const x2 = xR ?? x + 12");
lines.push("      const blocks = bar.swingOrderBlocks");
lines.push("      if (blocks && blocks.length > 0) {");
lines.push("        for (const ob of blocks) {");
lines.push("          const y1 = series.priceToCoordinate(ob.high)");
lines.push("          const y2 = series.priceToCoordinate(ob.low)");
lines.push("          if (y1 == null || y2 == null) continue");
lines.push("          obResult.push({");
lines.push("            x1: x, x2,");
lines.push("            y1: Math.min(y1, y2),");
lines.push("            y2: Math.max(y1, y2),");
lines.push("            fillColor: ob.bias > 0 ? this._colors.bullFill : this._colors.bearFill,");
lines.push("          })");
lines.push("        }");
lines.push("      }");
lines.push("      if (bar.fvgTop != null && bar.fvgBottom != null) {");
lines.push("        const y1 = series.priceToCoordinate(bar.fvgTop)");
lines.push("        const y2 = series.priceToCoordinate(bar.fvgBottom)");
lines.push("        if (y1 != null && y2 != null) {");
lines.push("          fvgResult.push({ x1: x, x2, y1: Math.min(y1, y2), y2: Math.max(y1, y2) })");
lines.push("        }");
lines.push("      }");
lines.push("      if (bar.equalHighs != null && !isNaN(bar.equalHighs)) {");
lines.push("        const y = series.priceToCoordinate(bar.equalHighs)");
lines.push("        if (y != null) eqhLines.push({ x, y })");
lines.push("      }");
lines.push("      if (bar.equalLows != null && !isNaN(bar.equalLows)) {");
lines.push("        const y = series.priceToCoordinate(bar.equalLows)");
lines.push("        if (y != null) eqlLines.push({ x, y })");
lines.push("      }");
lines.push("    }");
lines.push("    this._dd = { orderBlocks: obResult, fvgs: fvgResult, eqhLines, eqlLines }");
lines.push("");
lines.push("    if (this._data.length > 0) {");
lines.push("      const last = this._data[this._data.length - 1]");
lines.push("      if (last.premiumZoneTop != null && last.equilibrium != null) {");
lines.push("        const pTop = series.priceToCoordinate(last.premiumZoneTop)");
lines.push("        const pBot = series.priceToCoordinate(last.premiumZoneBottom!)");
lines.push("        const dTop = series.priceToCoordinate(last.discountZoneTop!)");
lines.push("        const dBot = series.priceToCoordinate(last.discountZoneBottom!)");
lines.push("        const eq = series.priceToCoordinate(last.equilibrium)");
lines.push("        if (pTop != null && pBot != null && dTop != null && dBot != null && eq != null) {");
lines.push("          zoneResult = {");
lines.push("            premiumTop: Math.min(pTop, pBot), premiumBottom: Math.max(pTop, pBot),");
lines.push("            discountTop: Math.min(dTop, dBot), discountBottom: Math.max(dTop, dBot),");
lines.push("            equilibrium: eq,");
lines.push("          }");
lines.push("        }");
lines.push("      }");
lines.push("    }");
lines.push("    this._zone = zoneResult");
lines.push("  }");
lines.push("");
lines.push("  paneViews(): readonly IPrimitivePaneView[] {");
lines.push("    return [new SmcPaneView(this._dd, this._zone)]");
lines.push("  }");
lines.push("}");
lines.push("");

lines.push("export interface SmcIndicatorConfig {");
lines.push("  enabled: boolean");
lines.push("  timeframes: Record<string, boolean>");
lines.push("  symbol: string");
lines.push("}");
lines.push("");

lines.push("interface SmcTimeframeState {");
lines.push('  series: ISeriesApi<"Line"> | null');
lines.push("  primitive: SmcPrimitive | null");
lines.push("  enabled: boolean");
lines.push("  data: SmcBarResult[]");
lines.push("}");
lines.push("");

lines.push("export function useSmcIndicator() {");
lines.push("  const stateMap = new Map<string, SmcTimeframeState>()");
lines.push("");
lines.push("  function getState(tf: string): SmcTimeframeState {");
lines.push("    let s = stateMap.get(tf)");
lines.push("    if (!s) {");
lines.push("      s = { series: null, primitive: null, enabled: false, data: [] }");
lines.push("      stateMap.set(tf, s)");
lines.push("    }");
lines.push("    return s");
lines.push("  }");
lines.push("");
lines.push("  async function fetchData(symbol: string, interval: string): Promise<SmcBarResult[]> {");
lines.push("    try {");
lines.push("      const now = Date.now()");
lines.push("      const from = now - 90 * 24 * 3600 * 1000");
lines.push("      const res = await getSmc({ symbol, interval, from, to: now })");
lines.push("      return res.data?.results ?? []");
lines.push("    } catch {");
lines.push("      return []");
lines.push("    }");
lines.push("  }");
lines.push("");
lines.push("  function init(chart: IChartApi, config: SmcIndicatorConfig): void {");
lines.push("    if (!config.enabled) return");
lines.push("    for (const [tf, enabled] of Object.entries(config.timeframes)) {");
lines.push("      if (!enabled) continue");
lines.push("      const state = getState(tf)");
lines.push("      if (state.series) continue");
lines.push('      const series = chart.addSeries("Line" as any, {');
lines.push('        color: "transparent",');
lines.push("        priceLineVisible: false,");
lines.push("        lastValueVisible: false,");
lines.push('      }) as ISeriesApi<"Line">');
lines.push("      const colors = TF_COLORS[tf] ?? TF_COLORS[\"1h\"]");
lines.push("      const barSec = TIMEFRAME_SECONDS[tf] ?? 3600");
lines.push("      const primitive = new SmcPrimitive(colors, barSec)");
lines.push("      series.attachPrimitive(primitive as any)");
lines.push("      state.series = series");
lines.push("      state.primitive = primitive");
lines.push("      state.enabled = true");
lines.push("      fetchData(config.symbol, tf).then((bars) => {");
lines.push("        state.data = bars");
lines.push("        primitive.setData(bars)");
lines.push("      })");
lines.push("    }");
lines.push("  }");
lines.push("");
lines.push("  function update(chart: IChartApi, config: SmcIndicatorConfig): void {");
lines.push("    const activeTfs = new Set(");
lines.push("      Object.entries(config.timeframes).filter(([, v]) => v).map(([k]) => k)");
lines.push("    )");
lines.push("    for (const [tf, state] of stateMap.entries()) {");
lines.push("      if (!activeTfs.has(tf) && state.series) {");
lines.push("        try { chart.removeSeries(state.series) } catch { }");
lines.push("        state.series = null");
lines.push("        state.primitive = null");
lines.push("        state.enabled = false");
lines.push("        state.data = []");
lines.push("      }");
lines.push("    }");
lines.push("    if (!config.enabled) return");
lines.push("    for (const tf of activeTfs) {");
lines.push("      const state = getState(tf)");
lines.push("      if (state.series) {");
lines.push("        if (state.primitive) state.primitive.setData(state.data)");
lines.push("        continue");
lines.push("      }");
lines.push('      const series = chart.addSeries("Line" as any, {');
lines.push('        color: "transparent",');
lines.push("        priceLineVisible: false,");
lines.push("        lastValueVisible: false,");
lines.push('      }) as ISeriesApi<"Line">');
lines.push("      const colors = TF_COLORS[tf] ?? TF_COLORS[\"1h\"]");
lines.push("      const barSec = TIMEFRAME_SECONDS[tf] ?? 3600");
lines.push("      const primitive = new SmcPrimitive(colors, barSec)");
lines.push("      series.attachPrimitive(primitive as any)");
lines.push("      state.series = series");
lines.push("      state.primitive = primitive");
lines.push("      state.enabled = true");
lines.push("      fetchData(config.symbol, tf).then((bars) => {");
lines.push("        state.data = bars");
lines.push("        primitive.setData(bars)");
lines.push("      })");
lines.push("    }");
lines.push("  }");
lines.push("");
lines.push("  function destroy(chart: IChartApi): void {");
lines.push("    for (const [, state] of stateMap.entries()) {");
lines.push("      if (state.series) {");
lines.push("        try { chart.removeSeries(state.series) } catch { }");
lines.push("      }");
lines.push("    }");
lines.push("    stateMap.clear()");
lines.push("  }");
lines.push("");
lines.push("  return { init, update, destroy }");
lines.push("}");
lines.push("");

const target = "F:/project/lenzeto/ai-frontend-web/src/composables/useSmcIndicator.ts";
const existing = fs.readFileSync(target, "utf8");
fs.writeFileSync(target, existing + lines.join("\n"), "utf8");
console.log("Appended " + lines.length + " lines to " + target);
