const fs = require("fs");
const lines = [];
lines.push('import { getSmc } from "@/api"');
lines.push('import type { Time, IChartApi, ISeriesApi, IPrimitivePaneView, IPrimitivePaneRenderer } from "lightweight-charts"');
lines.push('import type { CanvasRenderingTarget2D } from "fancy-canvas"');
lines.push("");
lines.push("interface SmcOrderBlock {");
lines.push("  high: number");
lines.push("  low: number");
lines.push("  time: number");
lines.push("  bias: number");
lines.push("}");
lines.push("");
lines.push("interface SmcBarResult {");
lines.push("  timestamp: number");
lines.push("  open: number");
lines.push("  high: number");
lines.push("  low: number");
lines.push("  close: number");
lines.push("  swingOrderBlocks: SmcOrderBlock[]");
lines.push("  fvgTop?: number");
lines.push("  fvgBottom?: number");
lines.push("  premiumZoneTop?: number");
lines.push("  premiumZoneBottom?: number");
lines.push("  discountZoneTop?: number");
lines.push("  discountZoneBottom?: number");
lines.push("  equilibrium?: number");
lines.push("  equalHighs?: number");
lines.push("  equalLows?: number");
lines.push("}");
lines.push("");
lines.push("interface ObRect {");
lines.push("  x1: number; x2: number");
lines.push("  y1: number; y2: number");
lines.push("  fillColor: string");
lines.push("}");
lines.push("");
lines.push("interface FvgRect {");
lines.push("  x1: number; x2: number");
lines.push("  y1: number; y2: number");
lines.push("}");
lines.push("");
lines.push("interface DrawData {");
lines.push("  orderBlocks: ObRect[]");
lines.push("  fvgs: FvgRect[]");
lines.push("  eqhLines: Array<{ x: number; y: number }>");
lines.push("  eqlLines: Array<{ x: number; y: number }>");
lines.push("}");
lines.push("");
lines.push("interface ZoneCoords {");
lines.push("  premiumTop: number; premiumBottom: number");
lines.push("  discountTop: number; discountBottom: number");
lines.push("  equilibrium: number");
lines.push("}");
lines.push("");
lines.push('const FVG_FILL = "rgba(241,196,15,0.25)"');
lines.push('const EQH_EQL_COLOR = "#8e44ad"');
lines.push("");
lines.push("const TF_COLORS: Record<string, { bullFill: string; bearFill: string }> = {");
lines.push('  "15m": { bullFill: "rgba(41,128,185,0.2)", bearFill: "rgba(192,57,43,0.2)" },');
lines.push('  "1h": { bullFill: "rgba(230,126,34,0.2)", bearFill: "rgba(192,57,43,0.2)" },');
lines.push('  "4h": { bullFill: "rgba(142,68,173,0.2)", bearFill: "rgba(192,57,43,0.2)" },');
lines.push('  "1D": { bullFill: "rgba(127,140,141,0.2)", bearFill: "rgba(192,57,43,0.2)" },');
lines.push("}");
lines.push("");
lines.push("const TIMEFRAME_SECONDS: Record<string, number> = {");
lines.push("  '15m': 15 * 60,");
lines.push("  '1h': 3600,");
lines.push("  '4h': 4 * 3600,");
lines.push("  '1D': 24 * 3600,");
lines.push("}");
lines.push("");

const code = lines.join("\n");
const target = "F:/project/lenzeto/ai-frontend-web/src/composables/useSmcIndicator.ts";
fs.writeFileSync(target, code, "utf8");
console.log("Wrote " + lines.length + " lines to " + target);
