-- 因子自动挖掘 - 任务表
CREATE TABLE IF NOT EXISTS `factor_mining_task` (
    `id` CHAR(36) PRIMARY KEY,
    `task_name` VARCHAR(100) NOT NULL,
    `symbol` VARCHAR(50) NOT NULL COMMENT '目标标的',
    `interval` VARCHAR(10) NOT NULL DEFAULT '1H' COMMENT 'K线周期',
    `operator_set` JSON NOT NULL COMMENT '算子集',
    `terminal_set` JSON NOT NULL COMMENT '终端集',
    `population_size` INT DEFAULT 500,
    `generations` INT DEFAULT 20,
    `tournament_size` INT DEFAULT 5,
    `crossover_prob` DOUBLE DEFAULT 0.8,
    `mutation_prob` DOUBLE DEFAULT 0.1,
    `parsimony_coefficient` DOUBLE DEFAULT 0.001,
    `fitness_metric` VARCHAR(20) DEFAULT 'RANK_IC',
    `lookback_bars` INT DEFAULT 500,
    `status` VARCHAR(20) DEFAULT 'PENDING' COMMENT 'PENDING/RUNNING/DONE/FAILED',
    `progress` DOUBLE DEFAULT 0 COMMENT '进度 0~1',
    `best_fitness` DOUBLE,
    `best_expression` TEXT,
    `best_expression_latex` VARCHAR(500),
    `error_msg` VARCHAR(500),
    `start_time` DATETIME NULL,
    `end_time` DATETIME NULL,
    `create_by` VARCHAR(64) DEFAULT NULL,
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_by` VARCHAR(64) DEFAULT NULL,
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `delete_flag` TINYINT(1) DEFAULT 0,
    INDEX idx_symbol (`symbol`),
    INDEX idx_status (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='因子挖掘任务表';

-- 候选因子表
CREATE TABLE IF NOT EXISTS `factor_candidate` (
    `id` CHAR(36) PRIMARY KEY,
    `task_id` CHAR(36) NOT NULL COMMENT '所属任务ID',
    `expression` TEXT NOT NULL COMMENT '因子表达式字符串',
    `expression_latex` VARCHAR(500) COMMENT 'LaTeX表达式',
    `fitness` DOUBLE NOT NULL COMMENT '适应度值',
    `rank_ic` DOUBLE COMMENT 'Rank IC',
    `sharpe` DOUBLE COMMENT '夏普比率',
    `turnover` DOUBLE COMMENT '换手率',
    `tree_depth` INT COMMENT '树深度',
    `node_count` INT COMMENT '节点数',
    `corr_with_label` DOUBLE COMMENT '与标签相关系数',
    `top_ret` DOUBLE COMMENT '分组收益',
    `selected` TINYINT(1) DEFAULT 0 COMMENT '是否保存为自定义特征',
    `custom_feature_name` VARCHAR(100) COMMENT '自定义特征名称',
    `create_by` VARCHAR(64) DEFAULT NULL,
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_by` VARCHAR(64) DEFAULT NULL,
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `delete_flag` TINYINT(1) DEFAULT 0,
    INDEX idx_task_id (`task_id`),
    INDEX idx_selected (`selected`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='候选因子表';
