CREATE TABLE `trade_signal` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `creator` varchar(255) DEFAULT NULL,
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(255) DEFAULT NULL,
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) DEFAULT b'0',
  `technical_signal_id` bigint DEFAULT NULL,
  `technical_signal_hash` varchar(255) DEFAULT NULL,
  `technical_signal_brief` varchar(255) DEFAULT NULL,
  `symbol` varchar(20) NOT NULL,
  `timeframe` varchar(10) DEFAULT NULL,
  `kline_time` varchar(19) DEFAULT NULL,
  `decision_reason` varchar(255) DEFAULT NULL,
  `risk_level` varchar(20) DEFAULT NULL,
  `position_ratio` decimal(10,4) DEFAULT NULL,
  `priority` tinyint DEFAULT '5',
  `order_action` varchar(20) DEFAULT NULL,
  `status` varchar(20) DEFAULT 'PENDING',
  `order_sn` varchar(64) DEFAULT NULL,
  `order_item_sn` varchar(64) DEFAULT NULL,
  `expected_price` decimal(20,8) DEFAULT NULL,
  `expected_amount` decimal(20,8) DEFAULT NULL,
  `stop_loss_price` decimal(20,8) DEFAULT NULL,
  `take_profit_price` decimal(20,8) DEFAULT NULL,
  `leverage` int DEFAULT NULL,
  `fee_rate` decimal(10,6) DEFAULT NULL,
  `executed_price` decimal(20,8) DEFAULT NULL,
  `executed_amount` decimal(20,8) DEFAULT NULL,
  `actual_fee` decimal(20,8) DEFAULT NULL,
  `executed_time` datetime DEFAULT NULL,
  `execution_note` varchar(500) DEFAULT NULL,
  `pnl_amount` decimal(20,8) DEFAULT NULL,
  `pnl_percentage` decimal(10,4) DEFAULT NULL,
  `close_time` datetime DEFAULT NULL,
  `holding_seconds` bigint DEFAULT NULL,
  `sharpe_ratio` decimal(10,4) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_technical_signal_id` (`technical_signal_id`),
  KEY `idx_technical_signal_hash` (`technical_signal_hash`),
  KEY `idx_status_symbol` (`status`,`symbol`),
  KEY `idx_order_sn` (`order_sn`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_kline_time` (`kline_time`),
  KEY `idx_symbol_timeframe` (`symbol`,`timeframe`),
  KEY `idx_risk_level` (`risk_level`),
  KEY `idx_priority` (`priority`),
  CONSTRAINT `trade_signal_ibfk_1` FOREIGN KEY (`technical_signal_id`) REFERENCES `technical_signal` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
